{
  imports = [
    ./angle.nix
    ./cli-pride-flags.nix
    ./gtt.nix
    ./ladybird.nix
    ./lockscreen-widgets.nix
    ./macchina.nix
    ./markmap.nix
    ./navi.nix
    ./pug.nix
    ./steam-rom-manager.nix
    ./tetrigo.nix
    ./webtorrent-cli.nix
    ./wtfutil.nix
    ./xenia.nix
    ./decky-plugins
    ./zellij-plugins
  ];
}
